import 'package:proyecto_ortiz_nosiglia_movil/models/appointment.dart';

final List<Appointment> appointments = [
  Appointment(
    id: '1',
    resourceType: 'Appointment',
    status: 'pendiente',
    cancellationReason: null,
    specialty: 'Dentista',
    reason: 'Checkeo',
    description: 'Cita de control mensual',
    previousAppointment: null,
    originatingAppointment: null,
    start: DateTime.now().subtract(const Duration(hours: 2)),
    end: DateTime.now().subtract(const Duration(hours: 1)),
    account: '1',
    cancellationDate: null,
    note: 'No hay ninguna nota',
    patientInstruction: 'Llegar 15 minutos antes',
    subject: 'Mendoza',
  ),
  Appointment(
    id: '2',
    resourceType: 'Appointment',
    status: 'cancelada',
    cancellationReason: null,
    specialty: 'Dentista',
    reason: 'Checkeo',
    description: 'Cita de control mensual',
    previousAppointment: null,
    originatingAppointment: null,
    start: DateTime.now().add(const Duration(hours: 2)),
    end: DateTime.now().add(const Duration(hours: 3)),
    account: '1',
    cancellationDate: DateTime.now().subtract(const Duration(hours: 1)),
    note: 'No hay ninguna nota',
    patientInstruction: 'Llegar 15 minutos antes',
    subject: 'Salamanca',
  ),
  Appointment(
    id: '3',
    resourceType: 'Appointment',
    status: 'completada',
    cancellationReason: null,
    specialty: 'Dentista',
    reason: 'Checkeo',
    description: 'Cita de control mensual',
    previousAppointment: null,
    originatingAppointment: null,
    start: DateTime.now().add(const Duration(hours: 2)),
    end: DateTime.now().add(const Duration(hours: 3)),
    account: '1',
    cancellationDate: DateTime.now().subtract(const Duration(hours: 1)),
    note: 'No hay ninguna nota',
    patientInstruction: 'Llegar 15 minutos antes',
    subject: 'Perez',
  ),
];
