import 'package:proyecto_ortiz_nosiglia_movil/models/appointment.dart';

final List<Appointment> appointments = [
  Appointment(
    id: '1',
    resourceType: 'Appointment',
    status: 'booked',
    cancellationReason: null,
    specialty: 'Dentistry',
    reason: 'Check-up',
    description: 'Annual dental check-up',
    previousAppointment: null,
    originatingAppointment: null,
    start: DateTime.now().subtract(const Duration(hours: 2)),
    end: DateTime.now().subtract(const Duration(hours: 1)),
    account: '12345',
    cancellationDate: null,
    note: 'No issues found',
    patientInstruction: 'Arrive 15 minutes early',
    subject: 'Patient 1',
    createdAt: DateTime.now().subtract(const Duration(days: 1)),
    updatedAt: DateTime.now(),
  ),
  Appointment(
    id: '2',
    resourceType: 'Appointment',
    status: 'cancelled',
    cancellationReason: 'Patient no-show',
    specialty: 'Dermatology',
    reason: 'Skin consultation',
    description: 'Consultation for skin issues',
    previousAppointment: null,
    originatingAppointment: null,
    start: DateTime.now().add(const Duration(hours: 2)),
    end: DateTime.now().add(const Duration(hours: 3)),
    account: '67890',
    cancellationDate: DateTime.now().subtract(const Duration(hours: 1)),
    note: 'Patient did not show up',
    patientInstruction: 'Reschedule appointment',
    subject: 'Patient 2',
    createdAt: DateTime.now().subtract(const Duration(days: 2)),
    updatedAt: DateTime.now(),
  ),
  // Añade más citas aquí si lo deseas
];
